title = "TDLX"
baseURL = 'https://tdlx.nl/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = 'G-8FHB8TCQ2D' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "TDLX"
  defaultColor = "dark" # set default color mode: dark or light
  description = "TDLX homepage"

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  intro = "TDLX's homepage"
  name = "Thomas D"
  description = "This is the homepage of TDLX a IT consultancy company"
  goToTop = true


[[params.socialIcons]]
name = "github"
url = "https://github.com/thomaskgb"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/tdelvaulx/"
