title = "TDLX"
baseURL = 'https://tdlx.nl/'
languageCode = 'en-us'

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = 'G-8FHB8TCQ2D' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    pageRef="experience"
    name = 'Experience'
    url = '/experience/'
    weight = 10
  [[menu.main]]
    pageRef="projects"
    name = 'Projects'
    url = '/projects/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "TDLX"
  defaultColor = "dark" # set default color mode: dark or light
  description = "TDLX homepage"

[params.author]
  avatar = "avatar.jpg"
  intro = "TDLX's homepage"
  name = "Thomas"
  footer = "TDLX Enterprise BV - Engineering Consultancy - BTW: BE 1010.144.439"
  description = "Hi, I am Thomas and I am glad you have found my personal website.\n Here you will find a little information about my background and experience, and some of the projects that keep me busy, both on professional missions and at home. Please reach out if you have any questions"
  goToTop = true


[[params.socialIcons]]
name = "github"
url = "https://github.com/thomaskgb"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/tdelvaulx/"
